name: Build Xcode Image

on:
  workflow_dispatch:
    inputs:
      xcode_version: 
        description: "Xcode Version:"
        required: true
        default: "13.4"

jobs:
  build:
      runs-on: macos-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Install dependencies 
          run: | 
            curl -L -o tart https://github.com/cirruslabs/tart/releases/latest/download/tart && sudo mv tart /usr/local/bin/tart && sudo chmod +x /usr/local/bin/tart
            brew tap hashicorp/tap
            brew install hashicorp/tap/packer
        
        - name: Packer init
          run: |
             packer init templates/xcode.pkr.hcl

        - name: Packer build
          run: |
            packer build -var xcode_version="${{ github.event.inputs.xcode_version }}" templates/xcode.pkr.hcl

        - name: Push to ghcr
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            GH_USERNAME: ${{ secrets.GH_USERNAME }}
            MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          run: |
            echo "::add-mask::$GH_USERNAME"
            echo "::add-mask::$GH_TOKEN"
            chmod +x tart.exp
            ./tart.exp 
            tart push monterey-xcode ghcr.io/Mo7amedFouad/monterey-xcode:${{ github.event.inputs.xcode_version }}
